### ISSUE TITLE
Inline Image Styling No Longer Works since Version 1.0.61

### ISSUE THREAD

**Issue by thorge** [andre-dietrich/liascript-preview-vscode#2]
I have noticed that since updating to version 1.0.61, the `liascript-preview` extension for VSCode no longer handles inline styling of images. This feature was working in previous versions.

Could you please clarify whether this functionality has been intentionally removed or if this is a bug that needs to be addressed?

**Steps to Reproduce:**
1. Install or update to `liascript-preview` version 1.0.61.
2. Attempt to apply inline styling to an image in a `.md` file, e.g.:
    ```
    ![image](image.png)<!-- style = "max-width: 25vw" -->
    ```
3. Observe that the styling is not applied as expected. Btw. this is the same with other html attributes.

**Expected Behavior:**
Inline styling of images should work as it did in versions prior to 1.0.61.

**Actual Behavior:**
The styling does not appear to be applied to images since 1.0.61.

**Environment:**
- VSCode version: 1.92.0
- OS: Ubuntu 22.04
- `liascript-preview` version: 1.0.61

Thank you for looking into this!

**Comment by andre-dietrich** [comment]
Thanks for this, this error should appear in all editors ... I fixed it ... and will try to upgrade all projects this evening ...

**Comment by andre-dietrich** [comment]
Should work as expected again ;-) ...

**Comment by thorge** [comment]
Tested with 1.0.65 and it works as expected :-) thanks for your quick help!
